# Generated by Django 5.1.3 on 2025-03-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_stockhistory_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockhistory',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
    ]
