# Generated by Django 5.1.3 on 2025-04-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salestransaction',
            name='product_stock',
        ),
        migrations.AddField(
            model_name='salestransaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('', 'Select Payment Method'), ('Cash', 'Cash'), ('Credit Card', 'Credit Card'), ('Bank Transfer', 'Bank Transfer')], max_length=20, null=True),
        ),
    ]
