# Generated by Django 5.1.3 on 2025-04-01 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_remove_salestransaction_product_stock_and_more'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product_stock',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stock.producttype'),
            preserve_default=False,
        ),
    ]
